### ISSUE TITLE
greece 

### ISSUE THREAD

**Issue by Nikos00076** [RoyaleAPI/family-config#1027]
```yaml
name: greece
key: https://royaleapi.com/clan/Q9LVJPC0
color: red
emblem: A_Char_Prince_01
My clan tag is #Q9LVGJPC0
```

**Comment by Zaop7** [comment]
> [!note]
> Please format your request as yaml file and attach it as an code in your request. Please follow also the given structure. You can find the instructions [here](https://github.com/RoyaleAPI/family-config/blob/master/README.md) or take inspiration from other issues.

**Comment by Zaop7** [comment]
The issue was closed due to inactivity.
