### ISSUE TITLE
Maratonci family-config

### ISSUE THREAD

**Issue by Merlin260677** [RoyaleAPI/family-config#1092]
name: Maratonci
key: MARAT
color: Purple
emblem: A_Char_Rocket_02
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    The **Maratonci** (MARAT) was formed 8 years ago

  Home to best players in Balkans
  We are 100% war clan, but serious about pushing ladder and path
  social:
   
    - discord: https://discord.gg/Vb8dr8Y5
  
clans:
  - name: Maratonci
    tag: #9LJJJRVC
  - name: Maratonci 2
    tag: #QYJ2YQR8
  - name: Maratonci 3
    tag: #RYPUUC8L

**Comment by Zaop7** [comment]
> [!note]
> Please format your request as yaml file and attach it as an code in your request. Please follow also the given structure. You can find the instructions [here](https://github.com/RoyaleAPI/family-config/blob/master/README.md) or take inspiration from other issues.

**Comment by Merlin260677** [comment]
name: Maratonci
key: MARAT
color: purple
emblem: A_Char_Rocket_02
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
   The Maratonci (MARAT) was formed 8 years ago

 Home to best players in Balkans
 We are 100% war clan, but serious about pushing ladder and path
  social:
 - discord: https://discord.gg/Vb8dr8Y5
clans:
clans:
name: Maratonci
tag: #9LJJJRVC
name: Maratonci 2
tag: #QYJ2YQR8
name: Maratonci 3
tag: #RYPUUC8L

**Comment by Merlin260677** [comment]
@Zaop7 Does this format work?
