### ISSUE TITLE
LES VIEUX SAGES 

### ISSUE THREAD

**Issue by Noalety** [RoyaleAPI/family-config#958]
Bonjour nous souhaiterions intégrer Royale api. Nous ne comprenons pas la procédure. Pourriez vous nous aider svp ?

**Comment by Zaop7** [comment]
Veuillez consulter la [page d'assistance](https://help.royaleapi.com/en/faq_clan_family.html) pour obtenir de la documentation et des exemples. Si vous ne comprenez pas quelque chose, dites-moi pourquoi.
