### ISSUE TITLE
FAMILIA AMIGOS SAIYAN 

### ISSUE THREAD

**Issue by andymod99** [RoyaleAPI/family-config#969]
name: Familia AMIGOS SAIYAN
key: FAMILIA-AS
color: blue 
emblem: Skull_05
description: Familia de 2 clanes, creados en 2019 y 2021. Somos clanes ladder y guerra, siempre en lucha por mejorar y superar cualquier adversidad. Si buscas un clan divertido y comprometido ¡ven a conocernos!
clans:
- name: AMIGOS SAIYAN
  tag: #Y2V9G02V
- name: AMIGOS SAIYAN 2
  tag: #YV0QUVY0

**Comment by Zaop7** [comment]
Please format your request as yaml file. You can find the instructions [here](https://github.com/RoyaleAPI/family-config/blob/master/README.md). You can take inspiration from other issues.

**Comment by Zaop7** [comment]
@andymod99 Please format the request correctly or i will close this issue.
